export const questionData = [
  // 🌍 GENERAL KNOWLEDGE — EASY
  { category: "General Knowledge", difficulty: "Easy", question: "What is the capital of France?", options: ["Paris", "Rome", "Madrid", "Berlin"], correct: "Paris" },
  { category: "General Knowledge", difficulty: "Easy", question: "How many continents are there on Earth?", options: ["5", "6", "7", "8"], correct: "7" },
  { category: "General Knowledge", difficulty: "Easy", question: "Which planet is known as the Red Planet?", options: ["Mars", "Venus", "Jupiter", "Earth"], correct: "Mars" },
  { category: "General Knowledge", difficulty: "Easy", question: "What do bees produce?", options: ["Honey", "Wax", "Milk", "Juice"], correct: "Honey" },
  { category: "General Knowledge", difficulty: "Easy", question: "What color are bananas when ripe?", options: ["Yellow", "Green", "Red", "Brown"], correct: "Yellow" },
  { category: "General Knowledge", difficulty: "Easy", question: "Which animal is known as man’s best friend?", options: ["Cat", "Dog", "Horse", "Elephant"], correct: "Dog" },
  { category: "General Knowledge", difficulty: "Easy", question: "Which shape has three sides?", options: ["Triangle", "Square", "Circle", "Hexagon"], correct: "Triangle" },
  { category: "General Knowledge", difficulty: "Easy", question: "Which season comes after summer?", options: ["Autumn", "Winter", "Spring", "Rainy"], correct: "Autumn" },
  { category: "General Knowledge", difficulty: "Easy", question: "Which day comes after Friday?", options: ["Saturday", "Sunday", "Thursday", "Monday"], correct: "Saturday" },
  { category: "General Knowledge", difficulty: "Easy", question: "Which instrument tells the time?", options: ["Clock", "Ruler", "Thermometer", "Scale"], correct: "Clock" },

  // 🌍 GENERAL KNOWLEDGE — MEDIUM
  { category: "General Knowledge", difficulty: "Medium", question: "Who wrote 'Romeo and Juliet'?", options: ["William Shakespeare", "Charles Dickens", "Jane Austen", "Mark Twain"], correct: "William Shakespeare" },
  { category: "General Knowledge", difficulty: "Medium", question: "Which country gifted the Statue of Liberty to the USA?", options: ["France", "Germany", "Canada", "Italy"], correct: "France" },
  { category: "General Knowledge", difficulty: "Medium", question: "In which year did World War II end?", options: ["1945", "1939", "1918", "1950"], correct: "1945" },
  { category: "General Knowledge", difficulty: "Medium", question: "Which ocean is the largest?", options: ["Pacific", "Atlantic", "Indian", "Arctic"], correct: "Pacific" },
  { category: "General Knowledge", difficulty: "Medium", question: "What is the boiling point of water at sea level?", options: ["100°C", "90°C", "110°C", "120°C"], correct: "100°C" },
  { category: "General Knowledge", difficulty: "Medium", question: "Which gas do plants absorb from the atmosphere?", options: ["Carbon Dioxide", "Oxygen", "Nitrogen", "Helium"], correct: "Carbon Dioxide" },
  { category: "General Knowledge", difficulty: "Medium", question: "Which instrument measures atmospheric pressure?", options: ["Barometer", "Thermometer", "Hygrometer", "Anemometer"], correct: "Barometer" },
  { category: "General Knowledge", difficulty: "Medium", question: "What is the largest mammal on Earth?", options: ["Blue Whale", "Elephant", "Giraffe", "Shark"], correct: "Blue Whale" },
  { category: "General Knowledge", difficulty: "Medium", question: "Who painted the Mona Lisa?", options: ["Leonardo da Vinci", "Van Gogh", "Michelangelo", "Picasso"], correct: "Leonardo da Vinci" },
  { category: "General Knowledge", difficulty: "Medium", question: "Which planet is the hottest in the solar system?", options: ["Venus", "Mercury", "Mars", "Jupiter"], correct: "Venus" },

  // 🌍 GENERAL KNOWLEDGE — HARD
  { category: "General Knowledge", difficulty: "Hard", question: "Which element has the symbol 'Au'?", options: ["Gold", "Silver", "Oxygen", "Aluminum"], correct: "Gold" },
  { category: "General Knowledge", difficulty: "Hard", question: "Which planet has the most moons?", options: ["Saturn", "Jupiter", "Uranus", "Neptune"], correct: "Saturn" },
  { category: "General Knowledge", difficulty: "Hard", question: "Who was the first man to step on the moon?", options: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins"], correct: "Neil Armstrong" },
  { category: "General Knowledge", difficulty: "Hard", question: "What is the longest river in the world?", options: ["Nile", "Amazon", "Yangtze", "Mississippi"], correct: "Nile" },
  { category: "General Knowledge", difficulty: "Hard", question: "What is the hardest natural substance?", options: ["Diamond", "Granite", "Iron", "Quartz"], correct: "Diamond" },
  { category: "General Knowledge", difficulty: "Hard", question: "What is the smallest country in the world?", options: ["Vatican City", "Monaco", "Malta", "Luxembourg"], correct: "Vatican City" },
  { category: "General Knowledge", difficulty: "Hard", question: "Which is the largest desert in the world?", options: ["Antarctica", "Sahara", "Gobi", "Arctic"], correct: "Antarctica" },
  { category: "General Knowledge", difficulty: "Hard", question: "Which scientist developed the theory of relativity?", options: ["Albert Einstein", "Isaac Newton", "Galileo Galilei", "Tesla"], correct: "Albert Einstein" },
  { category: "General Knowledge", difficulty: "Hard", question: "Which is the largest internal organ in the human body?", options: ["Liver", "Heart", "Brain", "Lungs"], correct: "Liver" },
  { category: "General Knowledge", difficulty: "Hard", question: "Which language has the most native speakers?", options: ["Mandarin Chinese", "English", "Spanish", "Hindi"], correct: "Mandarin Chinese" },

  // 🔬 SCIENCE — EASY
  { category: "Science", difficulty: "Easy", question: "What part of the plant conducts photosynthesis?", options: ["Leaf", "Stem", "Root", "Flower"], correct: "Leaf" },
  { category: "Science", difficulty: "Easy", question: "What gas do humans exhale?", options: ["Carbon Dioxide", "Oxygen", "Hydrogen", "Nitrogen"], correct: "Carbon Dioxide" },
  { category: "Science", difficulty: "Easy", question: "What planet is closest to the sun?", options: ["Mercury", "Venus", "Earth", "Mars"], correct: "Mercury" },
  { category: "Science", difficulty: "Easy", question: "Which part of the human body pumps blood?", options: ["Heart", "Lungs", "Liver", "Brain"], correct: "Heart" },
  { category: "Science", difficulty: "Easy", question: "Which organ helps you breathe?", options: ["Lungs", "Heart", "Kidney", "Stomach"], correct: "Lungs" },
  { category: "Science", difficulty: "Easy", question: "What is water’s chemical formula?", options: ["H₂O", "CO₂", "NaCl", "O₂"], correct: "H₂O" },
  { category: "Science", difficulty: "Easy", question: "What color is the sky on a clear day?", options: ["Blue", "Red", "Green", "Yellow"], correct: "Blue" },
  { category: "Science", difficulty: "Easy", question: "How many planets are in our solar system?", options: ["8", "7", "9", "10"], correct: "8" },
  { category: "Science", difficulty: "Easy", question: "Which planet is known as the Blue Planet?", options: ["Earth", "Neptune", "Uranus", "Mars"], correct: "Earth" },
  { category: "Science", difficulty: "Easy", question: "Which animal lays eggs?", options: ["Duck", "Cat", "Dog", "Horse"], correct: "Duck" },
  { category: "Science", difficulty: "Medium", question: "What planet is known as the Red Planet?", options: ["Mars", "Venus", "Earth", "Jupiter"], correct: "Mars" },
  { category: "Science", difficulty: "Medium", question: "Which part of the cell contains genetic material?", options: ["Nucleus", "Cytoplasm", "Cell wall", "Ribosome"], correct: "Nucleus" },
  { category: "Science", difficulty: "Medium", question: "Which vitamin is produced when sunlight hits the skin?", options: ["Vitamin D", "Vitamin A", "Vitamin C", "Vitamin B"], correct: "Vitamin D" },
  { category: "Science", difficulty: "Medium", question: "Which gas do humans exhale?", options: ["Carbon Dioxide", "Oxygen", "Hydrogen", "Nitrogen"], correct: "Carbon Dioxide" },
  { category: "Science", difficulty: "Medium", question: "What is the largest planet in our solar system?", options: ["Jupiter", "Saturn", "Earth", "Neptune"], correct: "Jupiter" },
  { category: "Science", difficulty: "Medium", question: "Who developed the theory of relativity?", options: ["Albert Einstein", "Newton", "Tesla", "Bohr"], correct: "Albert Einstein" },
  { category: "Science", difficulty: "Medium", question: "What is the center of an atom called?", options: ["Nucleus", "Proton", "Electron", "Neutron"], correct: "Nucleus" },
  { category: "Science", difficulty: "Medium", question: "Which metal is liquid at room temperature?", options: ["Mercury", "Iron", "Silver", "Copper"], correct: "Mercury" },
  { category: "Science", difficulty: "Medium", question: "What is the study of living things called?", options: ["Biology", "Physics", "Chemistry", "Geology"], correct: "Biology" },
  { category: "Science", difficulty: "Medium", question: "Which organ purifies blood in the human body?", options: ["Kidney", "Heart", "Liver", "Lungs"], correct: "Kidney" },
  { category: "Science", difficulty: "Hard", question: "What is the powerhouse of the cell?", options: ["Mitochondria", "Nucleus", "Ribosome", "Chloroplast"], correct: "Mitochondria" },
  { category: "Science", difficulty: "Hard", question: "What is the most abundant gas in Earth's atmosphere?", options: ["Nitrogen", "Oxygen", "Carbon Dioxide", "Argon"], correct: "Nitrogen" },
  { category: "Science", difficulty: "Hard", question: "What is the chemical symbol for Potassium?", options: ["K", "P", "Pt", "Po"], correct: "K" },
  { category: "Science", difficulty: "Hard", question: "Which part of the human brain controls balance?", options: ["Cerebellum", "Cerebrum", "Medulla", "Pons"], correct: "Cerebellum" },
  { category: "Science", difficulty: "Hard", question: "What is the speed of light in a vacuum?", options: ["299,792 km/s", "150,000 km/s", "1,000 km/s", "500,000 km/s"], correct: "299,792 km/s" },
  { category: "Science", difficulty: "Hard", question: "Which scientist proposed the three laws of motion?", options: ["Isaac Newton", "Albert Einstein", "Nikola Tesla", "Galileo Galilei"], correct: "Isaac Newton" },
  { category: "Science", difficulty: "Hard", question: "Which vitamin helps with blood clotting?", options: ["Vitamin K", "Vitamin D", "Vitamin A", "Vitamin B12"], correct: "Vitamin K" },
  { category: "Science", difficulty: "Hard", question: "What type of bond involves sharing of electron pairs between atoms?", options: ["Covalent Bond", "Ionic Bond", "Hydrogen Bond", "Metallic Bond"], correct: "Covalent Bond" },
  { category: "Science", difficulty: "Hard", question: "What is the hardest known natural material?", options: ["Diamond", "Graphene", "Quartz", "Corundum"], correct: "Diamond" },
  { category: "Science", difficulty: "Hard", question: "Which element has the highest melting point?", options: ["Tungsten", "Iron", "Platinum", "Carbon"], correct: "Tungsten" },
  // 🌎 GEOGRAPHY — EASY
{ category: "Geography", difficulty: "Easy", question: "Which is the largest continent?", options: ["Asia", "Africa", "Europe", "North America"], correct: "Asia" },
{ category: "Geography", difficulty: "Easy", question: "Which ocean is the largest?", options: ["Pacific", "Atlantic", "Indian", "Arctic"], correct: "Pacific" },
{ category: "Geography", difficulty: "Easy", question: "What is the capital of Japan?", options: ["Tokyo", "Osaka", "Kyoto", "Nagoya"], correct: "Tokyo" },
{ category: "Geography", difficulty: "Easy", question: "Which country is known as the Land of the Rising Sun?", options: ["Japan", "China", "Thailand", "Korea"], correct: "Japan" },
{ category: "Geography", difficulty: "Easy", question: "Which river flows through Egypt?", options: ["Nile", "Amazon", "Yangtze", "Mississippi"], correct: "Nile" },
{ category: "Geography", difficulty: "Easy", question: "Which is the largest country by area?", options: ["Russia", "Canada", "USA", "China"], correct: "Russia" },
{ category: "Geography", difficulty: "Easy", question: "Which continent is Egypt located in?", options: ["Africa", "Asia", "Europe", "Oceania"], correct: "Africa" },
{ category: "Geography", difficulty: "Easy", question: "What is the capital of Australia?", options: ["Canberra", "Sydney", "Melbourne", "Perth"], correct: "Canberra" },
{ category: "Geography", difficulty: "Easy", question: "Which sea separates Europe and Africa?", options: ["Mediterranean Sea", "Red Sea", "Black Sea", "Arabian Sea"], correct: "Mediterranean Sea" },
{ category: "Geography", difficulty: "Easy", question: "Which country has the most population?", options: ["China", "India", "USA", "Russia"], correct: "China" },

// 🌎 GEOGRAPHY — MEDIUM
{ category: "Geography", difficulty: "Medium", question: "Mount Everest is located in which mountain range?", options: ["Himalayas", "Andes", "Rockies", "Alps"], correct: "Himalayas" },
{ category: "Geography", difficulty: "Medium", question: "What is the capital city of Canada?", options: ["Ottawa", "Toronto", "Vancouver", "Montreal"], correct: "Ottawa" },
{ category: "Geography", difficulty: "Medium", question: "The Amazon rainforest is located in which country?", options: ["Brazil", "Peru", "Colombia", "Venezuela"], correct: "Brazil" },
{ category: "Geography", difficulty: "Medium", question: "Which desert is the largest in the world?", options: ["Antarctic Desert", "Sahara", "Arabian", "Gobi"], correct: "Antarctic Desert" },
{ category: "Geography", difficulty: "Medium", question: "Which US state is the largest by area?", options: ["Alaska", "Texas", "California", "Montana"], correct: "Alaska" },
{ category: "Geography", difficulty: "Medium", question: "Which river is the longest in the world?", options: ["Nile", "Amazon", "Yangtze", "Congo"], correct: "Nile" },
{ category: "Geography", difficulty: "Medium", question: "Which country has the Great Barrier Reef?", options: ["Australia", "Indonesia", "Philippines", "New Zealand"], correct: "Australia" },
{ category: "Geography", difficulty: "Medium", question: "What is the capital of South Africa?", options: ["Pretoria", "Cape Town", "Johannesburg", "Durban"], correct: "Pretoria" },
{ category: "Geography", difficulty: "Medium", question: "Which continent has the most countries?", options: ["Africa", "Europe", "Asia", "South America"], correct: "Africa" },
{ category: "Geography", difficulty: "Medium", question: "Which ocean lies between Africa and Australia?", options: ["Indian Ocean", "Atlantic Ocean", "Pacific Ocean", "Arctic Ocean"], correct: "Indian Ocean" },

// 🌎 GEOGRAPHY — HARD
{ category: "Geography", difficulty: "Hard", question: "What is the smallest country in the world?", options: ["Vatican City", "Monaco", "Malta", "Liechtenstein"], correct: "Vatican City" },
{ category: "Geography", difficulty: "Hard", question: "Which river flows through Baghdad?", options: ["Tigris", "Euphrates", "Jordan", "Nile"], correct: "Tigris" },
{ category: "Geography", difficulty: "Hard", question: "Which country has the most islands?", options: ["Sweden", "Norway", "Indonesia", "Philippines"], correct: "Sweden" },
{ category: "Geography", difficulty: "Hard", question: "Which mountain is known as the 'Savage Mountain'?", options: ["K2", "Everest", "Lhotse", "Makalu"], correct: "K2" },
{ category: "Geography", difficulty: "Hard", question: "What is the deepest ocean trench?", options: ["Mariana Trench", "Tonga Trench", "Java Trench", "Puerto Rico Trench"], correct: "Mariana Trench" },
{ category: "Geography", difficulty: "Hard", question: "What is the driest place on Earth?", options: ["Atacama Desert", "Sahara", "Gobi", "Namib"], correct: "Atacama Desert" },
{ category: "Geography", difficulty: "Hard", question: "Which city is known as the City of Canals?", options: ["Venice", "Amsterdam", "Bruges", "Bangkok"], correct: "Venice" },
{ category: "Geography", difficulty: "Hard", question: "Which country has three capitals?", options: ["South Africa", "Bolivia", "Australia", "Malaysia"], correct: "South Africa" },
{ category: "Geography", difficulty: "Hard", question: "What is the longest mountain range in the world?", options: ["Andes", "Himalayas", "Rockies", "Alps"], correct: "Andes" },
{ category: "Geography", difficulty: "Hard", question: "What country is the Danube River mostly associated with?", options: ["Germany", "Austria", "Hungary", "Romania"], correct: "Germany" },

// 📜 HISTORY — EASY
{ category: "History", difficulty: "Easy", question: "Who was the first President of the United States?", options: ["George Washington", "Abraham Lincoln", "Thomas Jefferson", "John Adams"], correct: "George Washington" },
{ category: "History", difficulty: "Easy", question: "In which year did World War I start?", options: ["1914", "1918", "1939", "1945"], correct: "1914" },
{ category: "History", difficulty: "Easy", question: "Who discovered America?", options: ["Christopher Columbus", "Marco Polo", "Magellan", "Vasco da Gama"], correct: "Christopher Columbus" },
{ category: "History", difficulty: "Easy", question: "Who built the pyramids of Egypt?", options: ["Ancient Egyptians", "Romans", "Greeks", "Persians"], correct: "Ancient Egyptians" },
{ category: "History", difficulty: "Easy", question: "Which war ended in 1945?", options: ["World War II", "World War I", "Cold War", "Vietnam War"], correct: "World War II" },
{ category: "History", difficulty: "Easy", question: "Who was the first man to step on the moon?", options: ["Neil Armstrong", "Buzz Aldrin", "Yuri Gagarin", "Michael Collins"], correct: "Neil Armstrong" },
{ category: "History", difficulty: "Easy", question: "Where was Napoleon Bonaparte born?", options: ["Corsica", "France", "Italy", "Austria"], correct: "Corsica" },
{ category: "History", difficulty: "Easy", question: "Who wrote the US Declaration of Independence?", options: ["Thomas Jefferson", "Benjamin Franklin", "John Adams", "George Washington"], correct: "Thomas Jefferson" },
{ category: "History", difficulty: "Easy", question: "When did the Berlin Wall fall?", options: ["1989", "1991", "1979", "1969"], correct: "1989" },
{ category: "History", difficulty: "Easy", question: "Who was the British Prime Minister during World War II?", options: ["Winston Churchill", "Neville Chamberlain", "Clement Attlee", "Margaret Thatcher"], correct: "Winston Churchill" },

// 📜 HISTORY — MEDIUM
{ category: "History", difficulty: "Medium", question: "Who was known as the Maid of Orléans?", options: ["Joan of Arc", "Marie Antoinette", "Queen Victoria", "Elizabeth I"], correct: "Joan of Arc" },
{ category: "History", difficulty: "Medium", question: "In which country did the Industrial Revolution begin?", options: ["England", "Germany", "France", "USA"], correct: "England" },
{ category: "History", difficulty: "Medium", question: "Who discovered penicillin?", options: ["Alexander Fleming", "Louis Pasteur", "Isaac Newton", "Marie Curie"], correct: "Alexander Fleming" },
{ category: "History", difficulty: "Medium", question: "When did the American Civil War end?", options: ["1865", "1850", "1870", "1880"], correct: "1865" },
{ category: "History", difficulty: "Medium", question: "Who was the first Emperor of Rome?", options: ["Augustus", "Julius Caesar", "Nero", "Caligula"], correct: "Augustus" },
{ category: "History", difficulty: "Medium", question: "What empire was ruled by Genghis Khan?", options: ["Mongol Empire", "Roman Empire", "Ottoman Empire", "Persian Empire"], correct: "Mongol Empire" },
{ category: "History", difficulty: "Medium", question: "When did the Titanic sink?", options: ["1912", "1905", "1918", "1925"], correct: "1912" },
{ category: "History", difficulty: "Medium", question: "Who painted the ceiling of the Sistine Chapel?", options: ["Michelangelo", "Leonardo da Vinci", "Raphael", "Donatello"], correct: "Michelangelo" },
{ category: "History", difficulty: "Medium", question: "When did India gain independence?", options: ["1947", "1950", "1945", "1939"], correct: "1947" },
{ category: "History", difficulty: "Medium", question: "Who was the first female Prime Minister of the UK?", options: ["Margaret Thatcher", "Theresa May", "Elizabeth II", "Angela Merkel"], correct: "Margaret Thatcher" },
// 📜 HISTORY — HARD
{ category: "History", difficulty: "Hard", question: "Who was the first Emperor of China?", options: ["Qin Shi Huang", "Kublai Khan", "Sun Yat-sen", "Emperor Gaozu"], correct: "Qin Shi Huang" },
{ category: "History", difficulty: "Hard", question: "When did the French Revolution begin?", options: ["1789", "1776", "1804", "1812"], correct: "1789" },
{ category: "History", difficulty: "Hard", question: "Who was the longest-reigning British monarch before Queen Elizabeth II?", options: ["Queen Victoria", "King George III", "Queen Anne", "King Henry VIII"], correct: "Queen Victoria" },
{ category: "History", difficulty: "Hard", question: "Which treaty ended World War I?", options: ["Treaty of Versailles", "Treaty of Paris", "Treaty of Vienna", "Treaty of Utrecht"], correct: "Treaty of Versailles" },
{ category: "History", difficulty: "Hard", question: "Who was the first man to circumnavigate the globe?", options: ["Ferdinand Magellan", "Christopher Columbus", "James Cook", "Marco Polo"], correct: "Ferdinand Magellan" },
{ category: "History", difficulty: "Hard", question: "In which year did the Roman Empire fall?", options: ["476 AD", "410 AD", "532 AD", "589 AD"], correct: "476 AD" },
{ category: "History", difficulty: "Hard", question: "Who was the founder of the Ottoman Empire?", options: ["Osman I", "Mehmed II", "Suleiman the Magnificent", "Bayezid I"], correct: "Osman I" },
{ category: "History", difficulty: "Hard", question: "Which US president served during the Great Depression and World War II?", options: ["Franklin D. Roosevelt", "Herbert Hoover", "Harry S. Truman", "Woodrow Wilson"], correct: "Franklin D. Roosevelt" },
{ category: "History", difficulty: "Hard", question: "Who was the last pharaoh of Ancient Egypt?", options: ["Cleopatra VII", "Nefertiti", "Tutankhamun", "Ramses II"], correct: "Cleopatra VII" },
{ category: "History", difficulty: "Hard", question: "Who discovered the Rosetta Stone?", options: ["Napoleon's army", "British archaeologists", "Egyptian farmers", "Roman explorers"], correct: "Napoleon's army" },

// 💻 TECHNOLOGY — EASY
{ category: "Technology", difficulty: "Easy", question: "What does 'CPU' stand for?", options: ["Central Processing Unit", "Computer Power Unit", "Control Process Utility", "Central Performance Unit"], correct: "Central Processing Unit" },
{ category: "Technology", difficulty: "Easy", question: "Who founded Microsoft?", options: ["Bill Gates", "Steve Jobs", "Mark Zuckerberg", "Larry Page"], correct: "Bill Gates" },
{ category: "Technology", difficulty: "Easy", question: "Which company makes the iPhone?", options: ["Apple", "Samsung", "Google", "Nokia"], correct: "Apple" },
{ category: "Technology", difficulty: "Easy", question: "What does 'www' stand for in a website?", options: ["World Wide Web", "Wide World Web", "Web World Wide", "Wide Web World"], correct: "World Wide Web" },
{ category: "Technology", difficulty: "Easy", question: "What is the symbol for Wi-Fi?", options: ["Wave signal", "Circle", "Battery", "Arrow"], correct: "Wave signal" },
{ category: "Technology", difficulty: "Easy", question: "What is used to browse the internet?", options: ["Web Browser", "Compiler", "Processor", "Database"], correct: "Web Browser" },
{ category: "Technology", difficulty: "Easy", question: "What does USB stand for?", options: ["Universal Serial Bus", "Universal System Board", "User System Bridge", "Unified Signal Board"], correct: "Universal Serial Bus" },
{ category: "Technology", difficulty: "Easy", question: "Which company created Android?", options: ["Google", "Apple", "Microsoft", "IBM"], correct: "Google" },
{ category: "Technology", difficulty: "Easy", question: "Which social media uses the blue bird logo?", options: ["Twitter", "Facebook", "LinkedIn", "Snapchat"], correct: "Twitter" },
{ category: "Technology", difficulty: "Easy", question: "What does AI stand for?", options: ["Artificial Intelligence", "Advanced Interface", "Applied Innovation", "Automated Input"], correct: "Artificial Intelligence" },
// 💻 TECHNOLOGY — MEDIUM
{ category: "Technology", difficulty: "Medium", question: "Who co-founded Apple Inc. with Steve Jobs?", options: ["Steve Wozniak", "Bill Gates", "Jeff Bezos", "Larry Page"], correct: "Steve Wozniak" },
{ category: "Technology", difficulty: "Medium", question: "What programming language is primarily used for web page styling?", options: ["CSS", "HTML", "JavaScript", "Python"], correct: "CSS" },
{ category: "Technology", difficulty: "Medium", question: "Which company developed the Windows operating system?", options: ["Microsoft", "Apple", "IBM", "Intel"], correct: "Microsoft" },
{ category: "Technology", difficulty: "Medium", question: "What does 'HTTP' stand for?", options: ["HyperText Transfer Protocol", "High Transmission Text Protocol", "Hyperlink Transfer Process", "Host Text Transfer Path"], correct: "HyperText Transfer Protocol" },
{ category: "Technology", difficulty: "Medium", question: "Which programming language was created by Guido van Rossum?", options: ["Python", "C++", "Java", "Ruby"], correct: "Python" },
{ category: "Technology", difficulty: "Medium", question: "What does GPU stand for?", options: ["Graphics Processing Unit", "General Performance Utility", "Graphical Programming Unit", "Global Processing Utility"], correct: "Graphics Processing Unit" },
{ category: "Technology", difficulty: "Medium", question: "Which company owns YouTube?", options: ["Google", "Meta", "Amazon", "Microsoft"], correct: "Google" },
{ category: "Technology", difficulty: "Medium", question: "What is the function of a router?", options: ["Directs data traffic between networks", "Stores files", "Displays web pages", "Compiles programs"], correct: "Directs data traffic between networks" },
{ category: "Technology", difficulty: "Medium", question: "What is an algorithm?", options: ["A set of instructions to solve a problem", "A programming bug", "A software license", "A hardware device"], correct: "A set of instructions to solve a problem" },
{ category: "Technology", difficulty: "Medium", question: "What does HTML stand for?", options: ["HyperText Markup Language", "HighText Machine Learning", "Hyper Transfer Mode Language", "Host Transmission Markup Logic"], correct: "HyperText Markup Language" },
// 💻 TECHNOLOGY — HARD
{ category: "Technology", difficulty: "Hard", question: "What was the first programming language ever created?", options: ["Fortran", "Assembly", "COBOL", "C"], correct: "Fortran" },
{ category: "Technology", difficulty: "Hard", question: "In what year was the World Wide Web invented?", options: ["1989", "1991", "1985", "1995"], correct: "1989" },
{ category: "Technology", difficulty: "Hard", question: "Who is known as the father of the computer?", options: ["Charles Babbage", "Alan Turing", "Bill Gates", "John von Neumann"], correct: "Charles Babbage" },
{ category: "Technology", difficulty: "Hard", question: "What does BIOS stand for?", options: ["Basic Input Output System", "Binary Integrated Operating Software", "Basic Internal Operation Setup", "Base Input Output Storage"], correct: "Basic Input Output System" },
{ category: "Technology", difficulty: "Hard", question: "What does 'DNS' stand for?", options: ["Domain Name System", "Digital Network Service", "Data Node Server", "Domain Network Setup"], correct: "Domain Name System" },
{ category: "Technology", difficulty: "Hard", question: "Which company developed the Java programming language?", options: ["Sun Microsystems", "Microsoft", "IBM", "Apple"], correct: "Sun Microsystems" },
{ category: "Technology", difficulty: "Hard", question: "What is Moore’s Law about?", options: ["The number of transistors doubles every two years", "Computers double in speed every five years", "Data doubles every year", "AI improves exponentially each decade"], correct: "The number of transistors doubles every two years" },
{ category: "Technology", difficulty: "Hard", question: "Which protocol secures data over the internet?", options: ["HTTPS", "FTP", "SMTP", "POP3"], correct: "HTTPS" },
{ category: "Technology", difficulty: "Hard", question: "What does RAID stand for in computer storage?", options: ["Redundant Array of Independent Disks", "Rapid Access Indexed Data", "Random Array of Input Drives", "Read And Input Data"], correct: "Redundant Array of Independent Disks" },
{ category: "Technology", difficulty: "Hard", question: "What is quantum computing based on?", options: ["Qubits and superposition", "Binary logic", "Linear algorithms", "Digital switching"], correct: "Qubits and superposition" },

// 🏅 SPORTS — EASY
{ category: "Sports", difficulty: "Easy", question: "How many players are there in a football (soccer) team on the field?", options: ["11", "10", "9", "12"], correct: "11" },
{ category: "Sports", difficulty: "Easy", question: "What sport uses a bat, ball, and wickets?", options: ["Cricket", "Baseball", "Tennis", "Golf"], correct: "Cricket" },
{ category: "Sports", difficulty: "Easy", question: "Which country invented basketball?", options: ["USA", "Canada", "UK", "Australia"], correct: "USA" },
{ category: "Sports", difficulty: "Easy", question: "How many holes are there in a standard golf course?", options: ["18", "9", "12", "15"], correct: "18" },
{ category: "Sports", difficulty: "Easy", question: "In tennis, what is the term for a score of zero?", options: ["Love", "Nil", "Zero", "None"], correct: "Love" },
{ category: "Sports", difficulty: "Easy", question: "What color flag is waved to signal the end of a car race?", options: ["Checkered flag", "Red flag", "Yellow flag", "Green flag"], correct: "Checkered flag" },
{ category: "Sports", difficulty: "Easy", question: "Which sport is known as 'The Gentleman's Game'?", options: ["Cricket", "Golf", "Tennis", "Baseball"], correct: "Cricket" },
{ category: "Sports", difficulty: "Easy", question: "Which sport is played at Wimbledon?", options: ["Tennis", "Golf", "Football", "Rugby"], correct: "Tennis" },
{ category: "Sports", difficulty: "Easy", question: "What sport is associated with the FIFA World Cup?", options: ["Football (Soccer)", "Cricket", "Rugby", "Hockey"], correct: "Football (Soccer)" },
{ category: "Sports", difficulty: "Easy", question: "How many points is a touchdown worth in American football?", options: ["6", "3", "7", "10"], correct: "6" },
// 🏅 SPORTS — MEDIUM
{ category: "Sports", difficulty: "Medium", question: "Who holds the record for the most Olympic gold medals?", options: ["Michael Phelps", "Usain Bolt", "Carl Lewis", "Mark Spitz"], correct: "Michael Phelps" },
{ category: "Sports", difficulty: "Medium", question: "Which country hosted the 2016 Summer Olympics?", options: ["Brazil", "China", "UK", "Japan"], correct: "Brazil" },
{ category: "Sports", difficulty: "Medium", question: "In which sport would you perform a 'slam dunk'?", options: ["Basketball", "Volleyball", "Tennis", "Badminton"], correct: "Basketball" },
{ category: "Sports", difficulty: "Medium", question: "What is the highest possible break in snooker?", options: ["147", "155", "140", "150"], correct: "147" },
{ category: "Sports", difficulty: "Medium", question: "Which team has won the most FIFA World Cups?", options: ["Brazil", "Germany", "Italy", "Argentina"], correct: "Brazil" },
{ category: "Sports", difficulty: "Medium", question: "What sport uses terms like 'bogey' and 'birdie'?", options: ["Golf", "Cricket", "Baseball", "Tennis"], correct: "Golf" },
{ category: "Sports", difficulty: "Medium", question: "Who won the first modern Olympic Games in 1896?", options: ["Greece", "France", "UK", "USA"], correct: "Greece" },
{ category: "Sports", difficulty: "Medium", question: "What is the national sport of Japan?", options: ["Sumo wrestling", "Baseball", "Judo", "Karate"], correct: "Sumo wrestling" },
{ category: "Sports", difficulty: "Medium", question: "Which tennis player has the most Grand Slam titles (men)?", options: ["Novak Djokovic", "Roger Federer", "Rafael Nadal", "Pete Sampras"], correct: "Novak Djokovic" },
{ category: "Sports", difficulty: "Medium", question: "In cricket, how many runs are scored for hitting the ball over the boundary without bouncing?", options: ["6", "4", "5", "2"], correct: "6" },
// 🏅 SPORTS — HARD
{ category: "Sports", difficulty: "Hard", question: "Who was the first cricketer to score 100 international centuries?", options: ["Sachin Tendulkar", "Ricky Ponting", "Virat Kohli", "Brian Lara"], correct: "Sachin Tendulkar" },
{ category: "Sports", difficulty: "Hard", question: "Which country has won the most Rugby World Cups?", options: ["New Zealand", "South Africa", "Australia", "England"], correct: "South Africa" },
{ category: "Sports", difficulty: "Hard", question: "Which city hosted the first ever Olympic Games?", options: ["Athens", "Paris", "London", "Rome"], correct: "Athens" },
{ category: "Sports", difficulty: "Hard", question: "Who was the youngest Formula 1 World Champion?", options: ["Sebastian Vettel", "Lewis Hamilton", "Fernando Alonso", "Max Verstappen"], correct: "Sebastian Vettel" },
{ category: "Sports", difficulty: "Hard", question: "In which year did Roger Bannister break the 4-minute mile?", options: ["1954", "1960", "1948", "1956"], correct: "1954" },
{ category: "Sports", difficulty: "Hard", question: "Which country won the first ever FIFA World Cup in 1930?", options: ["Uruguay", "Brazil", "Germany", "Argentina"], correct: "Uruguay" },
{ category: "Sports", difficulty: "Hard", question: "Who has scored the most goals in World Cup history?", options: ["Miroslav Klose", "Pele", "Ronaldo Nazário", "Lionel Messi"], correct: "Miroslav Klose" },
{ category: "Sports", difficulty: "Hard", question: "Which NBA team has won the most championships?", options: ["Boston Celtics", "Los Angeles Lakers", "Chicago Bulls", "Golden State Warriors"], correct: "Boston Celtics" },
{ category: "Sports", difficulty: "Hard", question: "Who won the first ever Wimbledon Championship?", options: ["Spencer Gore", "William Renshaw", "Fred Perry", "Rod Laver"], correct: "Spencer Gore" },
{ category: "Sports", difficulty: "Hard", question: "Which female athlete has won the most Olympic medals?", options: ["Larisa Latynina", "Serena Williams", "Simone Biles", "Jackie Joyner-Kersee"], correct: "Larisa Latynina" },


];
